### ISSUE TITLE
Licence to make modifications on this repository 

### ISSUE THREAD

**Issue by nanduu04** [Psycojoker/pytest-capture-deprecatedwarnings#2]
Hey, 
I would like to fork this and make modifications to it but since you do not have any license, I am not able to use it. Could you maybe add an open-source license?  I have listed an [license ](https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt#:~:text=A%20short%20and%20simple%20permissive,terms%20and%20without%20source%20code.)that could be helpful for you.

**Comment by Psycojoker** [comment]
Hello,

Licence is MIT: https://github.com/Psycojoker/pytest-capture-deprecatedwarnings/blob/master/setup.py#L15

But I should probably add a real licence file yes.

**Comment by nanduu04** [comment]
thank you!
